### ISSUE TITLE
Add ability to run a dart project via "Run As"

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/dartboard#1]
We should add the ability to run a dart project via the run as context menus.

I've started implementing this in https://github.com/vogellacompany/eclipse-flutter/commit/b4b22d8d53b00631eb4463634f6ee8204ef776e3.

There should also be the ability to browse for a main file (e.g. main.dart) via a dialog.
Similiar to the java config page: 
![image](https://user-images.githubusercontent.com/5540255/48846582-c5dd5580-ed9f-11e8-9391-c79b1d1f0a4e.png)

**Comment by jonashungershausen** [comment]
TODO: 

- [ ] Add browse for file which opens a file browser in the currently selected project (project Combo)

**Comment by vogella** [comment]
Cool

Jonas Hungershausen <notifications@github.com> schrieb am Mi., 12. Juni
2019, 17:10:
