### ISSUE TITLE
Add dependency on Wild Web Developer

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/dartboard#108]
Many Dart developers will at least also edit `YAML` files. Most might do web dev as well, that's why I'd like to suggest, that we declare a dependency on WWD to allow an installing user to start straight away without installing another plugin as well. WDYT @vogella @mickaelistria?

**Comment by mickaelistria** [comment]
I think it's a good idea in general to ship the features users will use.
However, the question is on which artifact would you like to declare this dependency? I think if it's an optional dependency in the feature or something pre-installed in the IDE (assuming you plan to ship some dedicated `Eclipse IDE for Dart and Flutter developers`) it's fine; but I suggest you avoid a dependency anywhere else.
Also, beware that the YAML support in Eclipse Wild Web Developer isn't separated and is coming together with support for HTML, CSS, JS, JSON... so they will all come together.

**Comment by jonas-jonas** [comment]
> Also, beware that the YAML support in Eclipse Wild Web Developer isn't separated and is coming together with support for HTML, CSS, JS, JSON... so they will all come together.

Yeah, that's fine as many Dart (not Flutter) devs use it for web dev anyway. So having the support there out-of-the-box would be nice. 

> However, the question is on which artifact would you like to declare this dependency? I think if it's an optional dependency in the feature or something pre-installed in the IDE (assuming you plan to ship some dedicated Eclipse IDE for Dart and Flutter developers) it's fine; but I suggest you avoid a dependency anywhere else.

My thoughts were, that a user who installs Dartboard from the Marketplace (or updatesite) automatically adds WWD to their IDE.
I just saw, that it's shipped with the default eclipse Web dev bundle anyway? That would eliminate this issue for most. I, however, use I-Builds for most of my eclipse installs and I install the features/plugins I need separately, so it would be one updatesite/marketplace search less for me. But I'm not sure how common this use case is. 

> think if it's an optional dependency in the feature

I think this is what I'm talking about ^.

> assuming you plan to ship some dedicated Eclipse IDE for Dart and Flutter developers

That's a long term goal, yes.
