### ISSUE TITLE
Need to provide icon for dart content type

### ISSUE THREAD

**Issue by lak-proddev** [eclipse/dartboard#111]
After fixing the eclipse bug for content type-specific icons, We need to contribute icon using the extension point "org.eclipse.ui.genericeditor.icons".

https://bugs.eclipse.org/bugs/show_bug.cgi?id=513034

**Comment by vogella** [comment]
I think this can be added. Old releases will simply ignore that.

**Comment by vogella** [comment]
![image](https://user-images.githubusercontent.com/139910/63340489-771d1600-c347-11e9-99d5-89785ca3b0ed.png)
