### ISSUE TITLE
Pub support

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/dartboard#12]
The pub package manager should be supported natively.

**Comment by vogella** [comment]
I assume this issue is about the support for dependencies maintained in pubspec.yaml files.

What is the current process to use these if I want to use the Eclipse Dart editor?

**Comment by jonas-jonas** [comment]
Add them to the pubspec.yaml file and sync the project yourself (by running `pub get` on the command line). I'd like to run this command when the file is saved.

**Comment by vogella** [comment]
For the import: I believe the wizard code could do that in his
performFinish (or something similar) method.

Jonas Hungershausen <notifications@github.com> schrieb am Do., 18. Juli
2019, 11:17:

**Comment by jonas-jonas** [comment]
> For the import: I believe the wizard code could do that in his
performFinish (or something similar) method.

Yeah, I'm aware of the wizard. The problem is, that my registered Smartimport handler is not called if the project is imported as an Eclipse project, which is the case if the `.project` is present in the project.

**Comment by vogella** [comment]
Please add Mickael and ask for advice.

Jonas Hungershausen <notifications@github.com> schrieb am Do., 18. Juli
2019, 11:22:

**Comment by jonas-jonas** [comment]
Hi @mickaelistria,

I would like to run code on every import of a project, not just the first as that creates the `.project` file which turns a project directory into an Eclipse project in the `General->Projects from Folder or Archive` import wizards. See Attachments for what exactly I mean.

The best solution I've found is to extend the `EclipseProjectConfigurator` and override the `configure` method to run my code, but the class is not API. Are you aware of a better solution?

 [1] First import 
![image](https://user-images.githubusercontent.com/5540255/61448449-33ec1380-a953-11e9-9f95-5e0ea1a5b4bd.png)

[2] Second import 
![image](https://user-images.githubusercontent.com/5540255/61448535-5716c300-a953-11e9-9868-ecbd2bf81a3b.png)

**Comment by mickaelistria** [comment]
The wizard is designed in a way that if there is already a `.project` in the folder, it will be imported as it, without further configuration. It's a constraint and requirement for many things actually.
For your use-case (and similar ones), I think you would better hook a workspace listener, and listen to event of types `IResourceChangeEvent.POST_CHANGE` with delta of kind `IResourceDelta.ADDED` on a project. With this approach, you code would be invoked with any import strategy and not only with this wizard.

**Comment by jonas-jonas** [comment]
Thanks, I thought about that too, especially since we do need to also listen to save events on the file. Is there a way to register such listener without an Activator class @vogella @mickaelistria?

**Comment by vogella** [comment]
Eager activated OSGi service should work.

Jonas Hungershausen <notifications@github.com> schrieb am Do., 18. Juli
2019, 12:12:

**Comment by mickaelistria** [comment]
I wouldn't recommend using an Activator as you don't have any guarantee your plugin will be activated at import of a given folder. If it's not activated, Activator wasn't called yet, the listener isn't placed, and you don't get a notification for it.
I'd personally go for an extension to `org.eclipse.ui.startup`, making sure you schedule the work in a separate Job, otherwise you may freeze the UI during startup.

**Comment by vogella** [comment]
IMHO startup extension is outdated. Eager activated OSGi is much more
modern.

Mickael Istria <notifications@github.com> schrieb am Do., 18. Juli 2019,
12:17:

**Comment by jonas-jonas** [comment]
#107 Is merged. However there are still some issues, namely that we should use OSGi services instead of the startup extension. It will be tracked in a separate issue (https://github.com/eclipse/dartboard/issues/114).
