### ISSUE TITLE
Plugin problem

### ISSUE THREAD

**Issue by devanshhooda** [eclipse/dartboard#126]
I am unable to install the Dart plugin in my Eclipse IDE. 
An error is shown "unable to read repository" .

![Capture1](https://user-images.githubusercontent.com/43931542/63039393-d19a1a80-bee0-11e9-8ec2-bc2e3793e876.PNG)

**Comment by jonas-jonas** [comment]
You're trying to install an older version of the Dart plugin that is not maintained anymore. Please use this entry instead: https://marketplace.eclipse.org/content/dartboard

**Comment by vogella** [comment]
Where did you find the old link?

Jonas Hungershausen <notifications@github.com> schrieb am Mi., 14. Aug.
2019, 19:11:

**Comment by vogella** [comment]
Ah, found it. We are in process of deleting this outdated entry.
