### ISSUE TITLE
Allow to create launch configuration during attempt to start file

### ISSUE THREAD

**Issue by vogella** [eclipse/dartboard#130]
I select a Dart file and select Start as Dart application. Now I receive a dialog telling me that must create a launch configuration. Would be create if the dialog would allow to jump directly to a new Dart launch configuration. 

![image](https://user-images.githubusercontent.com/139910/63340243-de869600-c346-11e9-8bef-d0078ad6371f.png)

**Comment by jonas-jonas** [comment]
This actually was a bug. It should have selected the correct project and opened the create a launch config dialog.

**Comment by vogella** [comment]
Cool, thanks for the fast fix.

On Tue, Aug 20, 2019 at 12:51 PM Jonas Hungershausen
<notifications@github.com> wrote:
>
> This actually was a bug. It should have selected the correct project and opened the create a launch config dialog.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Eclipse Platform project co-lead
CEO vogella GmbH

Haindaalwisch 17a, 22395 Hamburg
Amtsgericht Hamburg: HRB 127058
Geschäftsführer: Lars Vogel, Jennifer Nerlich de Vogel
USt-IdNr.: DE284122352
Fax (040) 5247 6322, Email: lars.vogel@vogella.com, Web: http://www.vogella.com
