### ISSUE TITLE
Dartboard installation not suggested when opening *.dart files

### ISSUE THREAD

**Issue by PyvesB** [eclipse/dartboard#134]
Hello there!

I believe you're impacted by a bug similar to the one I was facing with [Eclipse Solargraph](https://github.com/PyvesB/eclipse-solargraph), [Bug 549637](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549637). I've raised [Bug 550424](https://bugs.eclipse.org/bugs/show_bug.cgi?id=550424) to address the more general case. This should give our plugins quite a bit of extra visibility and usage. 😉 

Cheers,

Pyves

**Comment by jonas-jonas** [comment]
Thanks for raising 550242 and notifying us. Is there anything we can do to help resolve this issue?

**Comment by PyvesB** [comment]
I don't know whether the code for _marketplace.eclipse.org_ is public. Anyway there's a dedicated team in the Foundation that maintains these community websites and I wouldn't expect the fix to be too hard, so I believe our best course of action is to wait for a bit!

**Comment by PyvesB** [comment]
Bug was promptly fixed, closing.
