### ISSUE TITLE
old entry https://marketplace.eclipse.org/content/dart-plugin-eclipse redirect (old plugin de facto delisted)

### ISSUE THREAD

**Issue by paulvi** [eclipse/dartboard#135]
There is issue about https://marketplace.eclipse.org/content/dart-plugin-eclipse redirect.
Below is my email response to Eclipse Marketplace

Hello (to Eclipse Marketplace)

This seems like fully unjust way to resolve claims on marketplace rating.
Now "Dart Plugin for Eclipse" is not possible to access at all, as it redirects.

Usually and it would be nicer to users, is to add as first line of older plugin description

> There is a new Dart Plugin for Eclipse on the
> marketplace[1] which is an Eclipse Project maintained by Eclipse Committers.

So unaware users can learn and make decision for themselves.
And as [2] would have link to [1] it should become lower in rating than [1]

Please remove redirect,
I have edited already.

It is also not nice for authors, that have not yet done any release, to start by removing alternatives.

Best regards,
Paul Verest

On 2019-08-26 9:56 PM, Marketplace Marketplace wrote:
> Hi Paul,
>
> As of recently, there is a new Dart Plugin for Eclipse on the
> marketplace[1] which is an Eclipse Project maintained by Eclipse
> Committers. It was requested by them to create a redirect from your
> plugin to theirs because yours is appearing higher is Google search
> results.
>
> Let me know if you have any questions and/or any issues with this request.
>
> Thanks.
>
> [1] - https://marketplace.eclipse.org/content/eclipse-dartboard-dart-development-eclipse
> [2] - https://marketplace.eclipse.org/content/dart-plugin-eclipse

ref #80, #82

**Comment by vogella** [comment]
Is your update site not broken anymore?

**Comment by paulvi** [comment]
update site broken question is unrelated to existence of 
https://marketplace.eclipse.org/content/dart-plugin-eclipse entry

The entry was created by me (in order not to google for Eclipse plugins), not by some Google team.  
If there is problem with that, there should be Google support (or its absence).
The entry can be updated with current status of google update site.

**Comment by jonas-jonas** [comment]
Hi Paul,

we requested the redirect, because your plugin is not downloadable nor installable _at all_. All users interested in Dart development in Eclipse would see your depleted marketplace entry, try to install it and see an error message. We even had users submitting issues on _our_ repository because _your_ plugin was not installable. 

This is why we requested the redirect.
Multiple requests were made by the marketplace and there was no response by you.
Thus they redirected the old link.

Could you please elaborate why the old entry should still be up?

**Comment by paulvi** [comment]
The plugin was by Google,
the https://marketplace.eclipse.org/content/dart-plugin-eclipse entry  was by me.

It is exactly purpose of marketplace entry, so that users can live feedback and find support.

Google may have stopped and remove the plugin for political reasons,   
you are acting not any better to users by trying to hide that there is/was other plugin.

The old entry should be, and point users to active project
and stay clearly about status.

**Comment by paulvi** [comment]
Besides, this plugin is "Eclipse plugin for Dart" #82 
not "Dart Plugin for Eclipse".

**Comment by vogella** [comment]
I think the foundation removes dead marktplace entries in general as keeping dead marktplace entries is really bad for the Eclipse ecosystem and the Eclipse users.

I contacted the foundation staff via email and ask them to comment in this ticket.

**Comment by paulvi** [comment]
@vogella Lars, that is incorrect statement.
Marketplace has maybe million on entries,
and only less than 900 are installed (via MPC), see https://marketplace.eclipse.org/metrics/successful_installs/last30days?page=17

I never heard or saw Eclipse (more specifically Marketplace maintainer) deleting or cleaning up old entries.

Note that in context of Dart development, you are biased, not neutral.

Eclipse mar

**Comment by vogella** [comment]
@paulvi we are talking about a plug-in here. But lets see what the Foundation says, I would be surprised if the foundation keeps dead update sites, that would IMHO be very bad for users.

This has nothing to do with being biased. Please stop such claims.

**Comment by paulvi** [comment]
De facto old plugin is not listed already. Search does not show it
https://marketplace.eclipse.org/search/site/dart

Lars, 4 years ago, Eclipse committers for main Eclipse project did not even care to list their own Eclipse project on marketplace, it was pain just to add tomcat plugins (without known proper Eclipse name)
I had to add things like https://marketplace.eclipse.org/content/eclipse-jst-server-adapters-apache-tomcat-jonas-j2ee

Now I see Eclipse committers start by removing alternatives from marketplace ?

Again, my points:

0. **It is not by any plugin author to decide if their plugin should appear above other alternatives.** 
And especially just because you as authors are closer to Eclipse foundation than other plugin authors. 

> It was requested by them to create a redirect from your
plugin to theirs because yours is appearing higher is Google search
results.

It is unjust, and smell really like bad behavior.
@vogella And now you are telling me, that this about for care of users, 
when initially it was just to put plugin above other alternative ?

1. This project has not done 0.1, 0.2, 0.3 releases (Is it only one 0.1 now?)
2. This project is "Eclipse plugin for Dart" #82, not old "Dart Plugin for Eclipse".

**Comment by vogella** [comment]
Paul, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=509929 for retirement of dead plug-ins.

**Comment by paulvi** [comment]
Well, I guess, nobody would care to find sources for older plugin,
at least I could find mirror for docs
http://dartdoc.takyam.com/tools/eclipse-plugin/

**Comment by paulvi** [comment]
From https://github.com/dart-lang/sdk/issues/702 dated 2012

> The Dart Editor Plugin for Eclipse is officially ready for early preview!

So again, don't go out by using old name.
That will be confusion for users,
especially if they tried older before, and than get something else instead of what they have expected.  
That will not be care about users,
so no redirect should be from "Dart Editor Plugin for Eclipse" or "Dart Plugin for Eclipse"

**Comment by vogella** [comment]
Paul, lets see what the foundation has to say. Deletion or redirect, we do not care. Keeping dead marketplace entries is IMHO a no go. 

Sp öets wait what Christopher and Eric from the Eclipse foundation marketplace think.

**Comment by chrisguindon** [comment]
The foundation regularly audit listings for multiple reasons. For example, the membership team will audit listings to make sure that the "Eclipse Foundation Member Organization" field is only set to "Yes" by Eclipse Member.

As mentioned by @vogella, the community is also involved in helping us find invalid listings via https://bugs.eclipse.org/bugs/show_bug.cgi?id=509929.

It's important for us to keep the Eclipse Marketplace relevant by making sure that our listings are valid, up-to-date and that there is not duplicates.

@paulvi could you explain the difference between Dart Editor Plugin for Eclipse and Dart Plugin for Eclipse and the reasoning to why we need both on Eclipse Marketplace?

**Comment by paulvi** [comment]
Hello Chris

To be clearer, I would explain in this way

"Dart (Editor) Plugin for Eclipse" was plugin started within Dart project
see dart-lang/sdk#702 dated 2012
It is currently, unavailable.  
As old marketplace entry is redirecting (unavailable), it is not possible to say when it did happen.  
Location of sources is yet unknown.

This repository holds 
"Dartboard, Eclipse plugin for Dart and Flutter development"
https://github.com/eclipse/dartboard/issues/136#issuecomment-534004233
It is new and distinct plugin, and should not be called "Dart (Editor) Plugin for Eclipse" to avoid confusions.

https://dart.dev/tools now only mentions and has link to Dartboard,  
so old plugin is signed off.

Old marketplace entry has got note with link to this newer plugin on Sept 2nd.  
That is the best thing developers of older plugin can do to give wave to newer effort.  
On the other side, if developers of new project start by removing traces of older project,  it seem no so good, IMHO. Usually there should be train of releases, for users to be sure they can switch.

**Comment by chrisguindon** [comment]
@paulvi based off the link you posted, the "Dart (Editor) Plugin for Eclipse" was never officially released and not much as been done since 2012.

> if developers of new project start by removing traces of older project, it seem no so good, IMHO. Usually there should be train of releases, for users to be sure they can switch.

+ the update site from your listing simply does not work:
http://www.dartlang.org/eclipse/update/channels/stable/

It's bad for the user experience if we allow our users to install listings in MPC that cannot be installed. For these reasons, we won't bring back the broken listing.

**Comment by vogella** [comment]
Nothing left to do here.

**Comment by paulvi** [comment]
> the update site from your listing simply does not work:
http://www.dartlang.org/eclipse/update/channels/stable/

so was known before

with older entry it would be possible to tell, when it did happen

Any ways, enough discussions have happened, let be closed.
