### ISSUE TITLE
https://github.com/eclipse/dartboard repository metadata

### ISSUE THREAD

**Issue by paulvi** [eclipse/dartboard#136]
Please consider to https://github.com/eclipse/dartboard metadata as
"Dartboard is an Eclipse plugin for Dart"
or
"Dartboard is an Eclipse plugin for Dart and Flutter development."

It is even better than "Dart Plugin for Eclipse" (expression not used),
as this plugin is produced within Eclipse.

Currently it is "Dart integration into Eclipse",
that is a bit not common expression.

ref #82

**Comment by jonas-jonas** [comment]
We changed the description on the repository and added a few tags. Thanks for the suggestion.

**Comment by paulvi** [comment]
well, now "Dart Plugin for Eclipse" at top (GitHub metadata)  
and  
"Eclipse plugin for Dart" in README

**Comment by jonas-jonas** [comment]
Do you mean this part: _Dartboard is an Eclipse plugin for Dart and Flutter development._?

If so that is intended as it's a description in a whole sentence of what the plugin is supposed to do. And it's true because Dartboard **is** an **Eclipse plugin** for **Dart and Flutter development**.

**Comment by paulvi** [comment]
I mean README is good, but GitHub metadata still reads:

> Dart Plugin for Eclipse

i.e. older/ confusing intro

Please update metadata with e.g.
"Dartboard is an Eclipse plugin for Dart and Flutter development."
