### ISSUE TITLE
Pomless Tycho build fails on Windows

### ISSUE THREAD

**Issue by androidworx** [eclipse/dartboard#142]
This is an issue which was observed on Windows, but not Linux. 
[dartboard-error.txt](https://github.com/eclipse/dartboard/files/3586536/dartboard-error.txt)
In a pomless build, a temporary .polyglot.build.properties project file is created to act as the pom. I assume the issue arises on Windows because it handles multi-threading in a different way to Linux. The fix is to add a standard Tycho pom.xml of the appropriate packaging type for the project: "eclipse-plugin" for the plugin and "eclipse-feature" for the feature. 

Note that 2 errors were reported when using Maven version 3.6.2. With earlier version 3.5.4, 4 errors were reported, so the issue differs in how it is manifest according to which version of Maven is employed.

**Comment by jonas-jonas** [comment]
@vogella can you have a look?

**Comment by vogella** [comment]
Will setup a Windows machine soon so that I can test.

**Comment by vogella** [comment]
Just had the same error on Linux. I think you are running into a Maven bug, please try Maven. 3.6.0. 3.6.1 and or 3.6.2. have a bug. If this still does not work, please reopen.
