### ISSUE TITLE
Build fails with recent Maven releases (#142 re-opened)

### ISSUE THREAD

**Issue by androidworx** [eclipse/dartboard#143]
Re-opening [Pomless Tycho build fails on Windows](https://github.com/eclipse/dartboard/issues/142)

On Linux I have observed build failures with Maven versions v3.6.1 and v3.6.2
Attached file with summary of results:
[pomless-tycho-build-results.txt](https://github.com/eclipse/dartboard/files/3590353/pomless-tycho-build-results.txt)
Maven version v3.6.1 has a bug which causes dependency resolution to fail. Version v3.6.2 has a different bug which is to do with the pomless build. I have checked that on both Windows and Linux, adding a pom.xml file to both the plugin and feature projects provides a trivial work around.

**Comment by vogella** [comment]
Does it work with 3.6.0?

**Comment by androidworx** [comment]
Works with 3.6.0. I see my comment did not make this emphatic: "First 4 lines on console show .polyglot.build.properties created and readable." is the expected result when there is no pomless build issue.

**Comment by vogella** [comment]
3.6.1 and 3.6.2 are buggy so nothing we can do here.
