### ISSUE TITLE
Subfolder not considered during launch configuration creation

### ISSUE THREAD

**Issue by vogella** [eclipse/dartboard#144]
I'm following https://www.vogella.com/tutorials/Dart/article.html#exercise-developing-server-and-frontend and used Vscode to create the structure.

Afterwards, I imported the project into Eclipse and tried to launch main.dart, located in the bin folder. Dartboard generates a launch configuration but does not include the path, so I get the following error:

Error: Error when reading 'file:///home/vogella/workspace/dart2/gerritreader/server/main.dart': No such file or directory

![image](https://user-images.githubusercontent.com/139910/64534630-15344880-d316-11e9-8eec-2c1d17db8e04.png)

Manually adding bin does also not work.

**Comment by jonas-jonas** [comment]
I think this particular issue was due to you importing the top level project, that had two separate projects beneath it. 

However we now automatically detect the entry point from stagehand (#170). So this should make the whole process easier.
