### ISSUE TITLE
Unable to find Dartboard in Eclipse Marketplace

### ISSUE THREAD

**Issue by njohnson-una** [eclipse/dartboard#147]
I would like to install, but have been unable.  I have additionally tried adding to available software sites in Eclipse configuration, but have had no luck installing this add-on.

Any help would be appreciated, thanks!

**Comment by jonas-jonas** [comment]
Hi, we are happy to help!

What version of eclipse are you using? We only support the latest version (2019-09), as we rely on code that is not available in older versions.

**Comment by njohnson-una** [comment]
Thank you very much, that was the key.  I wasn't on the latest version.
