### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by wimjongman** [eclipse/dartboard#155]
I have installed the javascript package from the eclipse downloads website and i'm trying to install dart development from nightly. It gives this error:

![image](https://user-images.githubusercontent.com/180969/71323591-2bd16a80-24d5-11ea-802c-97559d2731e7.png)

Cannot complete the install because of a conflicting dependency.
  Software being installed: Dartboard - Dart language support for Eclipse 0.1.0.201911211357 (org.eclipse.dartboard.feature.feature.group 0.1.0.201911211357)
  Software currently installed: Wild Web Developer - Developer and debug Web and Node applications 0.7.2.201911151547 (org.eclipse.wildwebdeveloper.feature.feature.group 0.7.2.201911151547)
  Only one of the following can be installed at once: 
    XML support using Language Server 0.4.1.201908202007 (org.eclipse.wildwebdeveloper.xml 0.4.1.201908202007)
    XML support using Language Server 0.5.0.201911151547 (org.eclipse.wildwebdeveloper.xml 0.5.0.201911151547)
  Cannot satisfy dependency:
    From: Dartboard - Dart language support for Eclipse 0.1.0.201911211357 (org.eclipse.dartboard.feature.feature.group 0.1.0.201911211357)
    To: org.eclipse.equinox.p2.iu; org.eclipse.wildwebdeveloper.feature.feature.group [0.4.2.201909061612,0.4.2.201909061612]
  Cannot satisfy dependency:
    From: Wild Web Developer - Web edition in Eclipse IDE (Experimental) 0.4.2.201909061612 (org.eclipse.wildwebdeveloper.feature.feature.group 0.4.2.201909061612)
    To: org.eclipse.equinox.p2.iu; org.eclipse.wildwebdeveloper.xml [0.4.1.201908202007,0.4.1.201908202007]
  Cannot satisfy dependency:
    From: Wild Web Developer - Developer and debug Web and Node applications 0.7.2.201911151547 (org.eclipse.wildwebdeveloper.feature.feature.group 0.7.2.201911151547)
    To: org.eclipse.equinox.p2.iu; org.eclipse.wildwebdeveloper.xml [0.5.0.201911151547,0.5.0.201911151547]

**Comment by wimjongman** [comment]
Reason being WWD is included in the dartboard feature. It should not be included because of version issues.

Also the build does not work. The orbit repository can no longer be found and build should be done agains the latest and greates.

**Comment by jonas-jonas** [comment]
Thanks for your PR. Closing, as it addressed these issues.
