### ISSUE TITLE
Dart SDK location referenced in tests not correct on Windows

### ISSUE THREAD

**Issue by cybersearch2** [eclipse/dartboard#162]
There are 2 tests that fail when run on Windows. The error messages are self-evident eg. `  DartPreferenceInitializerTest.preferenceStore__NormalStartup__CorrectDefaultsAreSet:43
  expected:<[/usr/lib/dart]> but was:<[C:\Program Files\Dart\dart-sdk]>`. 

I have created a pull request to fix this bug

**Comment by jonas-jonas** [comment]
Thanks for the fix!
