### ISSUE TITLE
Support --enable-vm-service flag for dart run

### ISSUE THREAD

**Issue by sebthom** [eclipse/dartboard#174]
To support hot code reload in dart projects we need to run dart with the '--enable-vm-service' flag. 

It does not seem to be possible to currently configure this for a Dart launcher.

**Comment by jonas-jonas** [comment]
Yes, that's correct. Feel free to provide a PR if you have time, otherwise this should be relatively easy to implement. Do you feel like it should be made configurable (e.g. a checkbox with "Enable Vm Service for Hot Reload")? Or just run every Dart launch with the flag?

**Comment by sebthom** [comment]
I think the most generic solution would be to provide a separate input field where you can provide additional dart vm options/flags. Like the JVM arguments in the Java launcher.

**Comment by jonas-jonas** [comment]
Yes, that should work. Though, I'd like to provide these "toggleable" options via a checkbox, rather than a text field. But it should be easily implemented. Will see if I find some time for this issue this week.
