### ISSUE TITLE
Core API-like feature

### ISSUE THREAD

**Issue by System0x20** [eclipse/dartboard#176]
I use Eclipse for PHP (and Java). It has a "PHP include path/CoreAPI" menu in Project Explorer view for each PHP project.
I'm now asking you genius programmers to add this feature to Dart plugin because I learnt PHP and Java by this feature and Code recommender
Please do me a favour and develop this feature as soon as possible.
PS:
1. I'd rather wait for this feature than using Intellij IDEA. I started programming with Eclipse I will end it with Eclipse.
2. Love you guys its too good for Alpha development status
3. I'm not English native so sorry for any mistake
4. My friends telling me to use Javascript but Google is right Javascript isn't a good solution so I need this feature to learn this C#/Erlang/Java/Smalltalk/PHP-like language its way easier than struggling to know what is prototype
Thank you

**Comment by vogella** [comment]
No plans to develop this, sorry. Code contributions are welcome
