### ISSUE TITLE
Eclipse preference Dart SDK location validation always false - wrong compare string

### ISSUE THREAD

**Issue by Nawakland** [eclipse/dartboard#179]
- Test on both Windows 7 and Debian 10 OS
- Eclipse v4.14
- Dart v2.10.3 <stable>

Today, the command **dart --version** return **Dart SDK version: 2.10.3 <stable> [...]**
So the compare string **return version.startsWith("Dart VM version");** is always false/not valid line 136 from file **org.eclipse.dartboard/src/org/eclipse/dartboard/preferences/DartSDKLocationFieldEditor.java**

I suggest to test if the keywords "Dart" and "version" appear in the compare string (and better compare both in lower case to avoid mismatch).

Tell me when it will be available in nighty build to start working with.

Best regards,
Nawakland.

![dartboard_issue](https://user-images.githubusercontent.com/56754835/98218041-92277600-1f4b-11eb-8c53-f1bbb2c54d7f.png)

**Comment by vogella** [comment]
@Nawakland thanks for the report. Could you send a PR for the fix?

**Comment by Nawakland** [comment]
@vogella What about nightly build ? Seems there is no update from commits.

**Comment by vogella** [comment]
@Nawakland sorry for this. I look into this on Friday, the next two days are already really busy.

**Comment by harshchokshi** [comment]
Any solution available.

Not a valid SDK Location?
