### ISSUE TITLE
[Eclipse 2023-03][macOS] installation fails due to dependency not found org.eclipse.mylyn.commons.notifications.core

### ISSUE THREAD

**Issue by kaplanski** [eclipse/dartboard#183]
Hi, I am running Eclipse 2023-03 on macOS/aarch64, I encountered the following error:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Dartboard - Dart language support for Eclipse 0.1.0.202001060850 (org.eclipse.dartboard.feature.feature.group 0.1.0.202001060850)
  Missing requirement: Language Server Protocol client for Eclipse IDE (Incubation) 0.13.0.201912071343 (org.eclipse.lsp4e 0.13.0.201912071343) requires 'osgi.bundle; org.eclipse.mylyn.commons.notifications.core 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Dartboard - Dart language support for Eclipse 0.1.0.202001060850 (org.eclipse.dartboard.feature.feature.group 0.1.0.202001060850)
    To: org.eclipse.equinox.p2.iu; org.eclipse.lsp4e [0.13.0.201912071343,0.13.0.201912071343]

**Comment by sebthom** [comment]
This project is outdated and currently dormant. You can give https://github.com/dart4e/dart4e/ a try.

**Comment by kaplanski** [comment]
> This project is outdated and currently dormant. You can give https://github.com/dart4e/dart4e/ a try.

Hi, thx for the advice, I'll give dart4e a try; current state being for the one project I have to do with dart I have temporarily switched to another IDE that supports Dart and the Flutter Framework.
