### ISSUE TITLE
Support dartfmt

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/dartboard#2]
There should be the ability to run clean up actions via https://github.com/dart-lang/dart_style.

I'm not sure if the cleanup actions of eclipse can be expanded for this, but if that possible we should use it. Otherwise we could also add an External Tool?

**Comment by DanTup** [comment]
You probably already noticed, but the LSP server can provide formatting (it uses dart_style internally) which should be much better than using an external tool (since there's no extra process to spawn and the server already has the contents of the file buffer) :-)

**Comment by DanTup** [comment]
Yeah, I thought that might be the case from the date - just wanted to make sure you knew and didn't spend time trying to spawn an external tool if you don't need to :-)

Note: we don't support format-range though (the ServerCapabilities should advertise this) and it's always the standard dart_style rules (eg. 2 spaces). This is the same as if you used `dart_style` directly though.
