### ISSUE TITLE
Change light theme to something nicer

### ISSUE THREAD

**Issue by vogella** [eclipse/dartboard#21]

**Comment by jonas-jonas** [comment]
Is this fine for you?
![image](https://user-images.githubusercontent.com/5540255/60467133-fe0e1600-9c55-11e9-9936-aee19fffeb4a.png)

I opened https://github.com/eclipse/dartboard/pull/68. Feel free to check it out for your self.

**Comment by vogella** [comment]
Looks great

Jonas Hungershausen <notifications@github.com> schrieb am Mo., 1. Juli
2019, 23:19:

**Comment by jonas-jonas** [comment]
I also added a PR to upstream TM4E to improve the existing Eclipse light theme: https://github.com/eclipse/tm4e/pull/215

It should now look pretty similar to the standard eclipse theme. Not sure about the Dark theme though.
