### ISSUE TITLE
Set up build environment

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/dartboard#27]
https://ci.eclipse.org/dartboard/

@vogella Please setup the build job for the project on the eclipse CI infrastructure.

**Comment by vogella** [comment]
Any issues your are facing with creating the job? Should be super easy.

**Comment by jonas-jonas** [comment]
For now we should wait for the move the EF.

Lars Vogel <notifications@github.com> schrieb am Mi., 5. Juni 2019, 11:33:

**Comment by jonas-jonas** [comment]
I've setup a build job for the master branch here: https://ci.eclipse.org/dartboard/job/dartboard/

The next steps should be to:
- Active the github pull request verify plugin (https://wiki.eclipse.org/Jenkins#GitHub_Pull_Request_Builder_Plugin)
- Publish "nightly" builds on downloads.eclipse.org (https://wiki.eclipse.org/Jenkins#How_do_I_deploy_artifacts_to_download.eclipse.org.3F)
...

**Comment by vogella** [comment]
As an example to provide the update site:

https://ci.eclipse.org/windowbuilder/job/org.eclipse.windowbuilder/

**Comment by vogella** [comment]
Fixed?
