### ISSUE TITLE
Quick fixes show "No suggestions available" even though there are options shown

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/dartboard#3]
![image](https://user-images.githubusercontent.com/5540255/51187130-7321a500-18db-11e9-8c8a-03006bcded91.png)

**Comment by jonas-jonas** [comment]
Related https://bugs.eclipse.org/bugs/show_bug.cgi?id=517681

**Comment by lak-proddev** [comment]
The original bug was fixed. I hope fix should be available incoming release.
http://git.eclipse.org/c/platform/eclipse.platform.text.git/commit/?id=301800e75274f26d94d01da866550c188f0d8eb1

**Comment by jonas-jonas** [comment]
Confirmed.
