### ISSUE TITLE
Unknown Method textDocument/didSave

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/dartboard#32]
When saving a file, the analysis server sends an error indicating that it doesn't support the method `textDocumnet/didSave`. According to https://github.com/dart-lang/sdk/issues/36464 it's an error in the client (should be fixed in LSp4E).

**Comment by vogella** [comment]
IIRC this was fixed in the LSp4E? Please add link to the bugreport / commit.

**Comment by jonas-jonas** [comment]
Not yet, didn't push the fix for the version mismatch yet. 

Bug is here https://bugs.eclipse.org/bugs/show_bug.cgi?id=548210

**Comment by jonas-jonas** [comment]
Merged into lsp4e. https://git.eclipse.org/r/#/c/143922/
