### ISSUE TITLE
Request use of Dart logo

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/dartboard#34]
For use for launch configurations, and other places inside the plugin.

I requested the use of the icon asset with the eclipse foundation.

**Comment by vogella** [comment]
Bug report?

**Comment by jonas-jonas** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=548210

**Comment by vogella** [comment]
Bug reference points to Don't send textDocument/didSave notifications if the server does not support it?

**Comment by jonas-jonas** [comment]
Whoops, sorry: http://dev.eclipse.org/ipzilla/show_bug.cgi?id=20229

**Comment by vogella** [comment]
@mit-mit contacted via email and awaiting response from Google legal.

**Comment by jonas-jonas** [comment]
Our request has been approved. Now waiting for the Eclipse foundation.

**Comment by messi01** [comment]
Dartboard is approved to use the correct Dart logo. (found [here](https://drive.google.com/corp/drive/folders/1KXNtO9My2AMpDOF9A9Y_4aj4_BcgmDDT))
