### ISSUE TITLE
Use CBI license feature for dartboard

### ISSUE THREAD

**Issue by vogella** [eclipse/dartboard#40]
![image](https://user-images.githubusercontent.com/139910/60001979-05d32680-9668-11e9-9fd8-96273bc16bab.png)

We should use the CBI license feature from the foundation.  See here https://wiki.eclipse.org/CBI#CBI_license_bundle

**Comment by vogella** [comment]
@jonas-jonas looks like I cannot assign you to an issue. Can you?

**Comment by jonas-jonas** [comment]
> @jonas-jonas looks like I cannot assign you to an issue. Can you?

Hm, weird. Maybe you're not part of the admin team of the repository?

**Comment by jonas-jonas** [comment]
Done, we should also sign the artifacts, as I'm getting a warning before installation.
