### ISSUE TITLE
Dart console not closed after execution

### ISSUE THREAD

**Issue by vogella** [eclipse/dartboard#46]
Looks like the Dart Console is not getting closed / reused after program execution.

![image](https://user-images.githubusercontent.com/139910/60005361-9f9dd200-966e-11e9-959a-8461b5b2042f.png)

**Comment by jonas-jonas** [comment]
I would like to use a ProcessConsole for a bash process spawned via ProcessBuilder. ProcessConsole however seems to not be API accessible. Is there a different way to use the Console or a different class I have overlooked?

**Comment by lak-proddev** [comment]
> I would like to use a ProcessConsole for a bash process spawned via ProcessBuilder. ProcessConsole however seems to not be API accessible. Is there a different way to use the Console or a different class I have overlooked?

ProcessConsole should be used for the process launched by launch configuration. 
I think,  in future we need to launch the "Run As" --> "Run File" using launch configuration. Instead of directly calling using 
org.eclipse.dartboard.launch.LaunchUtil.launchDartFile(String, IPath)

It will handle some other operation like console mechanism,  save alert  (pull/76), etc...

**Comment by PPazderski** [comment]
Using launch configurations is a good idea but not required in any case. It might not obvious but all you need to do is adding the created process to a launch object (see my pull request). Eclipse automagically does all the required stuff to create a console and manage the process streams.

**Comment by lak-proddev** [comment]
> Using launch configurations is a good idea but not required in any case. It might not obvious but all you need to do is adding the created process to a launch object (see my pull request). Eclipse automagically does all the required stuff to create a console and manage the process streams.

Yes, I agree. that's what I mean to say. I mean, either launch or launch config. 

But, there was already code for the customized console. I just want to use the same console without intact. I really don't know why that was created. We shouldn't ignore it with alternate way right?

With this change, I think there is no new console needed. Can remove "consoleFactories" extension point and other classes.

@jonas-jonas  Can you check it ?. I am fine with the solution. But, think about the new console which was added earlier.

**Comment by jonas-jonas** [comment]
I like @PPazderski's approach better. I think it's very clean and doesn't require us to roll our own console. Also it gives us the cancel button for consoles which was my primary goal with a new console.

I've added a comment to the PR @PPazderski, after that we should be good to go.

**Comment by jonas-jonas** [comment]
Closed via #93
