### ISSUE TITLE
If SDK is entered after the file creation no errors/warnings are shown

### ISSUE THREAD

**Issue by vogella** [eclipse/dartboard#47]
If SDK is entered after the file creation no errors/warnings are shown. To test:

Start Eclipse with new workspace and ensure that the Dart SDK is not yet entered for this workspace
Create a new file
````
void main() {
	var bike = new Bicycle(2, 0, 1);
	print(bike);
}
````

-> No errors shows and the SDK is not yet available.

Now enter the SDK location and switch back to the Editor -> still no errors are shown.

**Comment by jonas-jonas** [comment]
For now if the SDK is entered a dialog will be shown, prompting the user to restart the IDE on the spot. I will add another warning if the user opens a dart file with no SDK installed.

**Comment by jonas-jonas** [comment]
I added a check if a valid SDK is entered. This should be solved now.
