### ISSUE TITLE
Add "New Dart file" & "New Dart project" to "New" context menu

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/dartboard#6]
The "new" context menu in the package explorer should show the option to generate a dart project as well as dart files.

**Comment by lak-proddev** [comment]
I can help for it. If you can provide some more details.

**Comment by jonas-jonas** [comment]
Hi, thanks for your interest.

We would like to provide a "new project wizard" for Dart projects. See the new project wizard and actions in the classic eclipse IDE for inspiration. 

The user should be able to select the directory (location), name and dart sdk version. In the future we would like to also add the ability to use templates (from the stagehand CLI #16). For now the wizard should just provide the basic tasks mentioned above.

If you're interested in working on this, see [1] for more inspiration. 

[1] 
![image](https://user-images.githubusercontent.com/5540255/60360108-33f39600-99db-11e9-87f5-4a1cf68159ec.png)
