### ISSUE TITLE
Investigate icon situation for generic editor

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/dartboard#69]
Currently, the generic editor is locked on one icon. This can be very confusing for different content types. There were many proposals on changing this to be an extension. Full discussion is here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=513034

This would be a great addition to the feel of Dartboard.

**Comment by vogella** [comment]
Mickael ist looking for contributions :-)

Jonas Hungershausen <notifications@github.com> schrieb am Mo., 1. Juli
2019, 23:37:

**Comment by jonas-jonas** [comment]
@lak-proddev started work on this in platform.text: https://bugs.eclipse.org/bugs/show_bug.cgi?id=513034

**Comment by lak-proddev** [comment]
The upstream bug was fixed with this commit.
https://git.eclipse.org/c/platform/eclipse.platform.text.git/commit/?id=5dacb5c72fb91737feedb5f20ff741a078707c61

**Comment by lak-proddev** [comment]
SS after fix for Project explorer 
Bug 549665 - [generic editor] Package Explorer should support content-type specific icons for generic editor 

![Open-With](https://user-images.githubusercontent.com/39690425/62473900-5c7f6480-b7bf-11e9-948a-cfc6ba4c4a6e.png)
