### ISSUE TITLE
Add plugin to Eclipse Marketplace  

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/dartboard#80]

**Comment by vogella** [comment]
Please handle with prio

Jonas Hungershausen <notifications@github.com> schrieb am Mo., 8. Juli
2019, 15:20:

**Comment by jonas-jonas** [comment]
I added the plugin to the marketplace: https://marketplace.eclipse.org/content/dartboard 

It's currently under review.

**Comment by vogella** [comment]
Awesome, thanks

Jonas Hungershausen <notifications@github.com> schrieb am Di., 9. Juli
2019, 11:01:

**Comment by jonas-jonas** [comment]
Added https://marketplace.eclipse.org/content/dartboard
