### ISSUE TITLE
Dart hover waste screenspace

### ISSUE THREAD

**Issue by vogella** [eclipse/dartboard#81]
Dart hover waste screenspace. If you increase the hover, a lot of empty space is shown. See screenshot.

![dart-doc](https://user-images.githubusercontent.com/139910/60818389-da8b2400-a19d-11e9-9658-d39b05870192.png)

Most likely an upstream problem. @jonas-jonas or @lak-proddev please follow up.

**Comment by lak-proddev** [comment]
I think this is the related bug

> "when resizing a hover tooltip with multiple entries the upper entries might get hidden when the tooltip is resized (see screenshots)"

https://bugs.eclipse.org/bugs/show_bug.cgi?id=547733

Seems to be some content is hidden in your SS. I see additional content instead of blank space.

![image](https://user-images.githubusercontent.com/39690425/60830428-d2021000-a1d4-11e9-98ff-cb90d3a8cc8c.png)

**Comment by lak-proddev** [comment]
@jonas-jonas  I couldn't see on windows. Can you confirm it's specific to Linux?

**Comment by jonas-jonas** [comment]
![image](https://user-images.githubusercontent.com/5540255/60998841-0bb05380-a35a-11e9-9ddc-07029b33cf36.png)
This is what it looks like for me. The whitespace increases responsively to the size of the popup. See the gif below.
![Peek 2019-07-10 21-33](https://user-images.githubusercontent.com/5540255/60999023-73669e80-a35a-11e9-8c2c-8d7913ed22ab.gif)

**Comment by lak-proddev** [comment]
@jonas-jonas  Can you check it in windows VM to confirm it's specific to Linux?

**Comment by jonas-jonas** [comment]
It's not as bad, but definitely not perfect there either: 

The part under the horizontal line should not move. Both issues seem to be related, but I'm not sure how to debug these kinds of issues.

![hover-whitespace-waste](https://user-images.githubusercontent.com/5540255/62200460-c34aeb00-b385-11e9-87e6-e2fbceff9d7e.gif)

**Comment by jonas-jonas** [comment]
Doesn't happen anymore (Ubuntu 19.10, Eclipse 2020-03). Please reopen, if it appears again.
