### ISSUE TITLE
Promote usage of Eclipse Dart

### ISSUE THREAD

**Issue by vogella** [eclipse/dartboard#82]
As discussed, @jonas-jonas  please send:

- [x] Email to Andmore about this project
- [x] Blog about new marketplace entry
- [x] Tweet about new marketplace entry

**Comment by jonas-jonas** [comment]
>  Blog about new marketplace entry

I don't want to spam my blog with short posts about trivial things. I'd like to include it in the next regular update scheduled by the end of the week if that's okay with you.

**Comment by vogella** [comment]
Providing an official installation site is not trivial from the user
perspective. But of course it is up to you how to blog about it. :-)

Jonas Hungershausen <notifications@github.com> schrieb am Di., 9. Juli
2019, 16:21:

**Comment by jonas-jonas** [comment]
I added an entry to my latest blog update here: https://jonas-jonas.dev/posts/dartboard-third-update/

>  Email to Andmore about this project

I'd really like to ship Pub support first before promoting usage of the plugin to Flutter devs. Waiting for #12. 

Also, Flutter uses its own SDK for every project (as it's shipped in the project). Currently, this is not implemented in the plugin and makes working with multiple Flutter projects *very* tedious. I'd like to allow to configure projects as Flutter projects first.

**Comment by vogella** [comment]
Please update the marketplace entry so that it is more user focused:
````
Eclipse Dartboard: Dart development in Eclipse
````
See https://marketplace.eclipse.org/content/dart-plugin-eclipse for a good description and header.

The name "Dartboard" should not be on the page, as the user does not care how the project is called.

Please also add a link to Github and the issues.

https://marketplace.eclipse.org/content/eclipse-dartboard-dart-development-eclipse

**Comment by jonas-jonas** [comment]
> Please update the marketplace entry so that it is more user focused:

The title is already pretty descriptive. See [wwd](https://marketplace.eclipse.org/content/eclipse-wild-web-developer-html-css-javascript-typescript-nodejs-angular-json-yaml), [acute](https://marketplace.eclipse.org/content/eclipse-acute-c-development-tools), etc.

I do think we should use the branding _Eclipse Dartboard_ as it is not a generic name, which does help with recognizability.

 > Please also add a link to Github and the issues.

The support URL is the GitHub issues page.

Apart from your issues, I don't really think the Eclipse Marketplace offers great visibility for these kind of projects. No Dart developers would try Eclipse, as it's known as a Java IDE. 

Regardless I adapted the description of the Marketplace entry to better match what's offered.

**Comment by paulvi** [comment]
- [ ] do some 0.x releases, before 1.0 release #127

**Comment by jonas-jonas** [comment]
#127 is about our first release. The current community review is for our first release which is release 0.1: https://projects.eclipse.org/projects/tools.dartboard/releases/0.1

**Comment by paulvi** [comment]
Then only email to Andmore is left unchecked in this TODO list.
See https://accounts.eclipse.org/mailing-list/andmore-dev


https://github.com/eclipse/andmore/ repository is surprising still

**Comment by jonas-jonas** [comment]
Technically the scope of the original issue is done.
