### ISSUE TITLE
Auto-detect Dart SDK in preference page does not work for existing workspace 

### ISSUE THREAD

**Issue by vogella** [eclipse/dartboard#83]
As discussed if I start Eclipse for an existing workspace, the Dart SDK is wrongly configured as the WS location.

To test: Delete Dart SDK and restart Eclipse, check preference page.

**Comment by lak-proddev** [comment]
Some how 	Files.exist returns true for emply location	
```
Path path = Paths.get(location);
Files.exists(path)

```

**Comment by jonas-jonas** [comment]
> Some how Files.exist returns true for emply location

In my experience it returns true for all files *and* directories. That being said, if the input is empty it just uses the current working directory (in this case the workspace location). Both of these problems can be fixed if I find a way to verify that the entered file is a valid Dart SDK executable. Though I'm not sure about the best way to do this.

1. We could check the output of `/entered/path --version` with a pattern (as it will contain the phrase `Dart VM version...`)
2. Somehow check the signature of the file. 

Currently, I'm favoring 1. but I'm not sure how future proof this is, as the output could change and thus require us to change the pattern to match it again.

**Comment by lak-proddev** [comment]
@jonas-jonas  You can close this issue. Since the pull request was merged https://github.com/eclipse/dartboard/pull/85
