### ISSUE TITLE
NPE occurs when Dart SDK location changes on the preference page.

### ISSUE THREAD

**Issue by lak-proddev** [eclipse/dartboard#86]
Sometimes, NPE occurs when Dart SDK location changes on the preference page.

> java.lang.NullPointerException
> 	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.close(FilteredPreferenceDialog.java:646)
> 	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.close(WorkbenchPreferenceDialog.java:137)
> 	at org.eclipse.jface.preference.PreferenceDialog$7.run(PreferenceDialog.java:927)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
> 	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
> 	at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:889)
> 	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:466)
> 	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.okPressed(WorkbenchPreferenceDialog.java:158)
> 	at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:233)
> 	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
> 	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
> 	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
> 	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
> 	at org.eclipse.jface.window.Window.open(Window.java:799)
> 	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:66)
> 	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
> 	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
> 	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:412)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
> 	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
>

**Comment by jonas-jonas** [comment]
Seems to be an upstream issue? 

`			IHandlerService service = PlatformUI.getWorkbench().getService(IHandlerService.class);
			service.deactivateHandler(showViewHandler);`


This is what's on FilteredPreferenceDialog.java:646

**Comment by lak-proddev** [comment]
> Seems to be an upstream issue?
> 
> `	IHandlerService service = PlatformUI.getWorkbench().getService(IHandlerService.class); service.deactivateHandler(showViewHandler);`

No, restart operation should be asynchronous.
