### ISSUE TITLE
Unhandled event loop exception while typing in SDK location field on preference page

### ISSUE THREAD

**Issue by lak-proddev** [eclipse/dartboard#88]
STEPS:
1. Open 'Dart' preference page 
2. Type some invalid characters in the SDK location filed. For instance double quotes ".
3.  Unhandled event loop Exception is logging.

See error log for more details. 
[Unhandled.txt](https://github.com/eclipse/dartboard/files/3372481/Unhandled.txt)

**Comment by jonas-jonas** [comment]
Fixed via #83
