### ISSUE TITLE
BadLocationException while modifying the dart file

### ISSUE THREAD

**Issue by lak-proddev** [eclipse/dartboard#91]
STEPS:
1.Copy the text into a new dart file
[test123.txt](https://github.com/eclipse/dartboard/files/3376843/test123.txt)
2. Select the text from line number 4 to the end of the file and delete.
3. Exceptions are logging.
[Exceptions.txt](https://github.com/eclipse/dartboard/files/3376867/Exceptions.txt)

**Comment by jonas-jonas** [comment]
Seems to be the same exception: https://bugs.eclipse.org/bugs/show_bug.cgi?id=521809

I've also noticed this and will have a look into the LSP4E code that's responsible for this.

**Comment by lak-proddev** [comment]
There are two exceptions
Submitted changes to related repositories
https://github.com/eclipse/tm4e/issues/213
https://bugs.eclipse.org/bugs/show_bug.cgi?id=521809#c3

**Comment by lak-proddev** [comment]
Both issues on upstream are fixed.  So closing the issue.
