### ISSUE TITLE
Need a logger class to log errors and exceptions

### ISSUE THREAD

**Issue by lak-proddev** [eclipse/dartboard#96]
Now, we are logging any exceptions or errors. We need to log using a logger class.

**Comment by jonas-jonas** [comment]
Now, I'm still not quite sure why we need another Logger class. We use Slf4j+logback currently, and that works quite well IMO.
Most solutions I saw in the PR were quite hacky or unelegant. Is there a downside to SLF4J+logback (apart from the extra dep)?

Also @vogella, one solution I saw involved an Activator. That was the only one that looked quite promising. Would it be okay for you to implement an Activator for that? Or do you have another solution in mind?

**Comment by vogella** [comment]
I remember that we had a discussion about this? @jonas-jonas do you remember where we discussed the issue?

**Comment by vogella** [comment]
Also please provide an example in the code in which you would like to log.

**Comment by jonas-jonas** [comment]
Yes, on the PR: https://github.com/eclipse/dartboard/pull/97

https://github.com/eclipse/dartboard/blob/f8696b7718864fa23663afe5e95629864a6ce64d/org.eclipse.dartboard/src/org/eclipse/dartboard/propertytester/IsDartProjectPropertyTester.java#L54 For example.

**Comment by vogella** [comment]
Send an email to eclipse-dev for the preferred way of logging. See Bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=502360 for a lengthy discussion.

**Comment by jonas-jonas** [comment]
Here is an example, that we should use (maybe via an accessor shortcut à la `PlatformUtil.getLog(clazz)`): https://bugs.eclipse.org/bugs/show_bug.cgi?id=502360#c77

**Comment by vogella** [comment]
I plan to enhance it via https://bugs.eclipse.org/bugs/show_bug.cgi?id=550347

**Comment by jonas-jonas** [comment]
Seems like this landed. Closing.
